spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# Optional: Let Hibernate create/modify tables based on your entities
spring.jpa.hibernate.ddl-auto=update